In [36]:
# To enable labeling of videos in notebook
%matplotlib notebook 

import matplotlib.pyplot as plt
import mediapy as media
import numpy as np
import os
import seaborn as sns

from point_labeler import PointLabeler
from point_tracker import PointTracker
from tapnet.utils import viz_utils
from video_manager import VideoManager

In [37]:
# Specify folder paths
video_folder = "/home/daphne/Documents/GMA/data/Preprocessed_Videos"
labeled_keypoints_folder = "/home/daphne/Documents/GMA/codes/output/labelled_points"
merged_keypoints_folder = "/home/daphne/Documents/GMA/codes/output/merged"
tracked_keypoints_folder = "/home/daphne/Documents/GMA/codes/output/tracked_points"
cropped_videos_folder = "/home/daphne/Documents/GMA/data/Preprocessed_Videos_Cropped"
cropped_resized_videos_folder = "/home/daphne/Documents/GMA/data/Preprocessed_Videos_Cropped_Resized"

## Create and setup VideoManager object

In [38]:
# Create a video manage to hold all videos
video_manager = VideoManager()

In [39]:
# Add all videos as VideoObject to video_manager (optional flag )
video_manager.add_all_videos(video_folder, add_pt_data=True)  # Load class data (pt_data), not the videos themselves

In [40]:
video_manager.get_all_video_ids()

['07_F-_1_c',
 '35_F-_1_c',
 '28_F-_c',
 '28_F-_2_c',
 '11_F-_c',
 '35_F-_c',
 '49_F-_c',
 '21_F-_c',
 '23_F-_1_c',
 '47_F-_c',
 '35_F-_2_c',
 '23_F-_2_c',
 '45_F-_c',
 '28_F-_1_c',
 '07_F-_2_c',
 '44_F-_c',
 '07_F-_c',
 '23_F-_c',
 '20_PR_c',
 '47_PR_c',
 '29_PR_c',
 '01_PR_c',
 '50_PR_c',
 '11_PR_c',
 '08_PR_c',
 '49_PR_c',
 '28_PR_c',
 '16_PR_c',
 '19_PR_c',
 '57_PR_c',
 '07_PR_c',
 '27_PR_c',
 '09_PR_c',
 '22_PR_c',
 '54_PR_c',
 '43_PR_c',
 '40_PR_c',
 '18_PR_c',
 '10_PR_c',
 '35_PR_c',
 '40_FN_c',
 '17_FN_c',
 '24_FN_c',
 '06_FN_c',
 '31_FN_c',
 '19_FN_c',
 '04_FN_c',
 '42_FN_c',
 '37_FN_c',
 '34_FN_c',
 '26_FN_c',
 '16_FN_c',
 '09_FN_c',
 '36_FN_c',
 '30_FN_c',
 '18_FN_c',
 '39_FN_c',
 '29_FN_c',
 '08_FN_c',
 '10_FN_c',
 '38_FN_c',
 '46_FN_c',
 '48_FN_c',
 '25_N_c',
 '17_N_c',
 '51_N_c',
 '32_N_c',
 '05_N_c',
 '15_N_c',
 '14_N_c',
 '26_N_c',
 '31_N_c',
 '53_N_c',
 '33_N_c',
 '45_N_c',
 '34_N_c',
 '21_N_c',
 '59_N_c',
 '46_N_c',
 '56_N_c']

In [41]:
# Some random video as an example
video_id = '35_F-_c'

## Look at patient data

In [42]:
# -- get VideoObject from VideoManager based on video_id (i.e. filename without extension)
video_object = video_manager.get_video_object(video_id)

In [43]:
video_object.video_id

'35_F-_c'

In [44]:
video_object.patient_data.age_group

'older'

In [45]:
video_object.patient_data.health_status

'abnormal'

## Label video

In [11]:
# -- get VideoObject from VideoManager based on video_id (i.e. filename without extension)
video_object = video_manager.get_video_object(video_id)

In [12]:
# -- Load video
video_object.load_video()

Loading video 35_F-_c


In [13]:
# -- Label keypoints in video (once all points selected, run next cell)
frame_index = 0
video_object.label_and_store_keypoints(frame_index, task='extreme_keypoints')

<IPython.core.display.Javascript object>

In [14]:
# -- Labelled keypoints are saved in VideoObject
video_object.keypoint_labels

{0: {}}

In [15]:
# -- Save labelled points to file to use again in the future
video_object.save_keypoints_to_csv(os.path.join(labeled_keypoints_folder, f'{video_id}.csv'))
video_object.save_keypoints_to_json(os.path.join(labeled_keypoints_folder, f'{video_id}.json'))

FileNotFoundError: [Errno 2] No such file or directory: '/home/daphne/Documents/GMA/codes/output/labelled_points/35_F-_c.csv/35_F-_c.extreme_keypoints.csv'

In [ ]:
# -- Release video from memory
video_object.release_video()

## Track labelled points

In [28]:
# -- Create PointTracker to track points
tracker = PointTracker('../tapnet/checkpoints/tapir_checkpoint_panning.npy')

In [29]:
# -- Load VideoObject from VideoManager
video_object = video_manager.get_video_object(video_id)

In [30]:
# -- Define starting frame and tracking task (which keypoints to track)
frame_index = 0
task = 'extreme_keypoints'

In [31]:
# -- Load video
video_object.load_video()

Loading video 35_F-_c


In [112]:
video_object.load_keypoint_labels_from_folder(merged_keypoints_folder, 'extreme_keypoints', 'json')

In [113]:
video_object.keypoint_labels

{0: {'head top': {'x': 402, 'y': 695},
  'left elbow': {'x': 476, 'y': 905},
  'right elbow': {'x': 152, 'y': 882},
  'left wrist': {'x': 454, 'y': 825},
  'right wrist': {'x': 92, 'y': 897},
  'left knee': {'x': 389, 'y': 1224},
  'right knee': {'x': 172, 'y': 1199},
  'left ankle': {'x': 307, 'y': 1309},
  'right ankle': {'x': 185, 'y': 1294}}}

In [32]:
# -- Track points (loading the labelled points from labeled_keypoints_folder, not necessary if already loaded in VideoObject
try:
    video_object.track_points(
        tracker,
        frame_index, # from which index to track
        task, # choose which keypoints to track, all or only extreme ones (for cropping, speeds up the tracking since less points)
        merged_keypoints_folder, # optional: where from to load labelled points
        'json'
    )
except ValueError as e:
    print(e)  # Handle the error appropriately

No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)


In [33]:
## -- Tracked points are saved in self.tracking_data
video_object.tracking_data

{0: {'head top': [{'x': 403.2474446296692,
    'y': 698.005199432373,
    'visible': True},
   {'x': 402.62640595436096, 'y': 695.2086639404297, 'visible': True},
   {'x': 401.52186155319214, 'y': 695.6709480285645, 'visible': True},
   {'x': 402.6258587837219, 'y': 695.5141639709473, 'visible': True},
   {'x': 403.34049582481384, 'y': 696.2302207946777, 'visible': True},
   {'x': 404.83469009399414, 'y': 696.9916534423828, 'visible': True},
   {'x': 405.96105694770813, 'y': 697.2625350952148, 'visible': True},
   {'x': 406.3136601448059, 'y': 696.9462203979492, 'visible': True},
   {'x': 406.3112139701843, 'y': 697.4739074707031, 'visible': True},
   {'x': 405.27297377586365, 'y': 696.1027908325195, 'visible': True},
   {'x': 404.83893871307373, 'y': 696.0342979431152, 'visible': True},
   {'x': 404.79265451431274, 'y': 695.8508491516113, 'visible': True},
   {'x': 405.4237997531891, 'y': 696.8524932861328, 'visible': True},
   {'x': 405.8638858795166, 'y': 696.3588523864746, 'visible

In [34]:
# -- Save tracked points
video_object.save_tracked_points_to_csv(tracked_keypoints_folder)
video_object.save_tracked_points_to_json(tracked_keypoints_folder)

tracking_data saved to /home/daphne/Documents/GMA/codes/output/tracked_points/tracked_points_35_F-_c.csv
tracking_data dumped to /home/daphne/Documents/GMA/codes/output/tracked_points/tracked_points_35_F-_c.json


In [35]:
# -- Release video from memory
video_object.release_video()

Releasing video 35_F-_c


## Load tracked points and crop videos accordingly

In [59]:
# -- Load VideoObject from VideoManager
video_object = video_manager.get_video_object(video_id)

In [60]:
# -- Compute extreme coordinates according to tracked points for appropriate cropping
video_object.update_extreme_coordinates(tracked_keypoints_folder)

In [61]:
# -- Extreme coordinates are stored in self.extreme_coordinates
video_object.extreme_coordinates

{'leftmost': 83, 'topmost': 1388, 'rightmost': 580, 'bottommost': 685}

In [62]:
video_object.load_keypoint_labels_from_folder(merged_keypoints_folder, 'extreme_keypoints', 'json')

In [63]:
video_object.keypoint_labels

{0: {'head top': {'x': 402, 'y': 695},
  'left elbow': {'x': 476, 'y': 905},
  'right elbow': {'x': 152, 'y': 882},
  'left wrist': {'x': 454, 'y': 825},
  'right wrist': {'x': 92, 'y': 897},
  'left knee': {'x': 389, 'y': 1224},
  'right knee': {'x': 172, 'y': 1199},
  'left ankle': {'x': 307, 'y': 1309},
  'right ankle': {'x': 185, 'y': 1294}}}

In [64]:
cropped_keypoint_labels = {
    frame: {
        keypoint: {
            'x': coords['x'] - 20,
            'y': coords['y'] - 30
        }
        for keypoint, coords in frame_data.items()
    }
    for frame, frame_data in video_object.keypoint_labels.items()
}

In [65]:
cropped_keypoint_labels

{0: {'head top': {'x': 382, 'y': 665},
  'left elbow': {'x': 456, 'y': 875},
  'right elbow': {'x': 132, 'y': 852},
  'left wrist': {'x': 434, 'y': 795},
  'right wrist': {'x': 72, 'y': 867},
  'left knee': {'x': 369, 'y': 1194},
  'right knee': {'x': 152, 'y': 1169},
  'left ankle': {'x': 287, 'y': 1279},
  'right ankle': {'x': 165, 'y': 1264}}}

In [66]:
# -- Crop videos according to extreme coordinates
video_object.crop_and_resize_video(cropped_videos_folder, resize=True, resize_folder=cropped_resized_videos_folder, load_and_release_video=True)

Loading video 35_F-_c
wrote labeled keypoints in cropped video coordinate space to /home/daphne/Documents/GMA/codes/./output/labeled/35_F-_c.extreme_keypoints.cropped.json
wrote cropped video to /home/daphne/Documents/GMA/data/Preprocessed_Videos_Cropped/cropped_vid_35_F-_c.mp4
wrote cropped and resized video to /home/daphne/Documents/GMA/data/Preprocessed_Videos_Cropped_Resized/cropped_resized_vid_35_F-_c.mp4
Releasing video 35_F-_c


# Visualize labelled points (to update!)

In [14]:
# -- Load VideoObject from VideoManager
video_object = video_manager.get_video_object(video_id)

In [15]:
extreme_keypoints = ['head top', 'left elbow', 'right elbow',
                  'left wrist', 'right wrist',
                  'left knee', 'right knee',
                  'left ankle', 'right ankle']

all_body_keypoints = ['nose',
                           'head bottom', 'head top',
                           'left ear', 'right ear',
                           'left shoulder', 'right shoulder',
                           'left elbow', 'right elbow',
                           'left wrist', 'right wrist',
                           'left hip', 'right hip',
                           'left knee', 'right knee',
                           'left ankle', 'right ankle']

In [16]:
def create_bodypart_colormap(body_keypoints):
    # Use a matplotlib colormap
    colorpalette = sns.color_palette("hls", len(body_keypoints))  # 'tab20' is a good palette for distinct colors

    bodypart_colors = {
        body_keypoints[i]: colorpalette[i] for i in range(len(body_keypoints))
    }

    return bodypart_colors

colormap = create_bodypart_colormap(all_body_keypoints)

In [80]:
colormap

{'nose': (0.86, 0.3712, 0.33999999999999997),
 'head bottom': (0.86, 0.5547294117647059, 0.33999999999999997),
 'head top': (0.86, 0.7382588235294117, 0.33999999999999997),
 'left ear': (0.7982117647058823, 0.86, 0.33999999999999997),
 'right ear': (0.6146823529411763, 0.86, 0.33999999999999997),
 'left shoulder': (0.4311529411764704, 0.86, 0.33999999999999997),
 'right shoulder': (0.33999999999999997, 0.86, 0.43237647058823525),
 'left elbow': (0.33999999999999997, 0.86, 0.6159058823529412),
 'right elbow': (0.33999999999999997, 0.86, 0.7994352941176471),
 'left wrist': (0.33999999999999997, 0.7370352941176468, 0.86),
 'right wrist': (0.33999999999999997, 0.553505882352941, 0.86),
 'left hip': (0.33999999999999997, 0.369976470588235, 0.86),
 'right hip': (0.49355294117647014, 0.33999999999999997, 0.86),
 'left knee': (0.677082352941176, 0.33999999999999997, 0.86),
 'right knee': (0.86, 0.33999999999999997, 0.8593882352941175),
 'left ankle': (0.86, 0.33999999999999997, 0.6758588235294

In [77]:
def draw_points(points_dict, frame):
    fig = plt.figure(figsize=(10, 5))
    ax_image = fig.add_subplot(121)
    ax_image.imshow(frame)
                
    for keypoint in extreme_keypoints:
        if keypoint in points_dict:
            point = (points_dict[keypoint][0], points_dict[keypoint][1])
            if point is not None:
                color = colormap[keypoint]
                ax_image.plot(point[0], point[1], 'o', color=color)
    ax_image.axis('off')
    plt.draw()

In [61]:
video_object.load_tracked_points_from_folder(tracked_keypoints_folder, 'json')

In [62]:
video_object.tracking_data[0]

{'head top': [{'x': 403.2474446296692, 'y': 698.005199432373, 'visible': True},
  {'x': 402.62640595436096, 'y': 695.2086639404297, 'visible': True},
  {'x': 401.52186155319214, 'y': 695.6709480285645, 'visible': True},
  {'x': 402.6258587837219, 'y': 695.5141639709473, 'visible': True},
  {'x': 403.34049582481384, 'y': 696.2302207946777, 'visible': True},
  {'x': 404.83469009399414, 'y': 696.9916534423828, 'visible': True},
  {'x': 405.96105694770813, 'y': 697.2625350952148, 'visible': True},
  {'x': 406.3136601448059, 'y': 696.9462203979492, 'visible': True},
  {'x': 406.3112139701843, 'y': 697.4739074707031, 'visible': True},
  {'x': 405.27297377586365, 'y': 696.1027908325195, 'visible': True},
  {'x': 404.83893871307373, 'y': 696.0342979431152, 'visible': True},
  {'x': 404.79265451431274, 'y': 695.8508491516113, 'visible': True},
  {'x': 405.4237997531891, 'y': 696.8524932861328, 'visible': True},
  {'x': 405.8638858795166, 'y': 696.3588523864746, 'visible': True},
  {'x': 405.894

In [63]:
video_object.load_video()

In [75]:
# Create dictionary of points to draw and frame to draw on
index = 0
points_to_draw = {key: [value[index]['x'], value[index]['y']] for key, value in video_object.tracking_data[0].items() if len(value) > index and value[index]['visible'] == True}
frame = video_object.video[index]

In [76]:
for key, value in video_object.tracking_data[0].items():
    print('--')
    print(key, value[index]['x'], value[index]['y'])

--
head top 403.2474446296692 698.005199432373
--
left elbow 477.9678440093994 906.5750885009766
--
right elbow 153.52896809577942 886.1080741882324
--
left wrist 456.43410444259644 828.7743186950684
--
right wrist 92.67237603664398 899.7448539733887
--
left knee 389.44995760917664 1224.8979949951172
--
right knee 172.2862672805786 1200.6010437011719
--
left ankle 308.35041761398315 1311.6973114013672
--
right ankle 185.14142990112305 1295.1608276367188


In [65]:
points_to_draw

{'head top': {'x': 403.2474446296692, 'y': 698.005199432373, 'visible': True},
 'left elbow': {'x': 477.9678440093994,
  'y': 906.5750885009766,
  'visible': True},
 'right elbow': {'x': 153.52896809577942,
  'y': 886.1080741882324,
  'visible': True},
 'left wrist': {'x': 456.43410444259644,
  'y': 828.7743186950684,
  'visible': True},
 'right wrist': {'x': 92.67237603664398,
  'y': 899.7448539733887,
  'visible': True},
 'left knee': {'x': 389.44995760917664,
  'y': 1224.8979949951172,
  'visible': True},
 'right knee': {'x': 172.2862672805786,
  'y': 1200.6010437011719,
  'visible': True},
 'left ankle': {'x': 308.35041761398315,
  'y': 1311.6973114013672,
  'visible': True},
 'right ankle': {'x': 185.14142990112305,
  'y': 1295.1608276367188,
  'visible': True}}

In [78]:
# Visualize tracked points
draw_points(points_to_draw, frame)

<IPython.core.display.Javascript object>

In [81]:
# draw query_points on original image
from point_tracker import convert_select_point_dict_to_query_points
select_frame = index
fig, ax = plt.subplots(figsize=(10, 5))
ax.imshow(np.array(video_object.video[select_frame]))
# to convert must be in form {keypoint: [x, y], ...}

query_points = convert_select_point_dict_to_query_points(select_frame, points_to_draw) #-DC: still in global reference: from xy to tyx
color_list = [colormap[keypoint] for keypoint in points_to_draw.keys()]
ax.scatter(query_points[:, 2], query_points[:, 1], marker="o", color=color_list, s=25)
plt.show(block=False)

<IPython.core.display.Javascript object>

## Transform to cropped coords

In [85]:
# Create a video manage to hold all videos
cropped_video_manager = VideoManager()
# Add all videos as VideoObject to video_manager (optional flag )
cropped_video_manager.add_all_videos(cropped_videos_folder, add_pt_data=True)  # Load class data (pt_data), not the videos themselves

In [101]:
cropped_video_manager.get_all_video_ids()

['cropped_vid_35_F-_c']

In [102]:
cropped_video_id = 'cropped_vid_35_F-_c'

In [94]:
video_object = video_manager.get_video_object(video_id)

In [95]:
# shift selected points according to cropped image
video_object.update_extreme_coordinates(tracked_keypoints_folder)
x_min = video_object.extreme_coordinates['leftmost']
y_max = video_object.extreme_coordinates['topmost']
x_max = video_object.extreme_coordinates['rightmost']
y_min = video_object.extreme_coordinates['bottommost']

margin = 0.15  # 15% margin
x_margin = round(margin * (x_max - x_min))
y_margin = round(margin * (y_max - y_min))
largest_margin = max(x_margin, y_margin)

height, width = video_object.video.metadata.shape
min_x_crop, max_x_crop = (max(0, x_min - largest_margin - 1),
                          min(width, x_max + largest_margin + 1))
min_y_crop, max_y_crop = (max(0, y_min - largest_margin - 1),
                          min(height, y_max + largest_margin + 1))

# first dimension is 't'
query_points_crop = np.array([[0.0, cc[1]-min_y_crop, cc[2]-min_x_crop] for cc in query_points])

In [114]:
cropped_keypoint_labels = {
    frame: {
        keypoint: {
            'x': coords['x'] - min_x_crop,
            'y': coords['y'] - min_y_crop
        }
        for keypoint, coords in frame_data.items()
    }
    for frame, frame_data in video_object.keypoint_labels.items()
}

In [115]:
cropped_keypoint_labels

{0: {'head top': {'x': 402, 'y': 116},
  'left elbow': {'x': 476, 'y': 326},
  'right elbow': {'x': 152, 'y': 303},
  'left wrist': {'x': 454, 'y': 246},
  'right wrist': {'x': 92, 'y': 318},
  'left knee': {'x': 389, 'y': 645},
  'right knee': {'x': 172, 'y': 620},
  'left ankle': {'x': 307, 'y': 730},
  'right ankle': {'x': 185, 'y': 715}}}

In [96]:
print(query_points_crop)

[[  0.         119.00518799 403.24743652]
 [  0.         327.57507324 477.96783447]
 [  0.         307.10809326 153.52896118]
 [  0.         249.77429199 456.43411255]
 [  0.         320.74487305  92.67237854]
 [  0.         645.89794922 389.44995117]
 [  0.         621.60107422 172.28627014]
 [  0.         732.69726562 308.35040283]
 [  0.         716.16088867 185.14143372]]


In [103]:
cropped_video_object = cropped_video_manager.get_video_object(cropped_video_id)

In [109]:
cropped_video_object.load_video()

Loading video cropped_vid_35_F-_c


In [110]:
# draw query_points on cropped video
fig, ax = plt.subplots(figsize=(10, 5))
ax.imshow(np.array(cropped_video_object.video[select_frame]))
ax.scatter(query_points_crop[:, 2], query_points_crop[:, 1], marker="o", color=color_list, s=25)
plt.show(block=False)

<IPython.core.display.Javascript object>

## visualize cropped coordinates

In [46]:
all_body_keypoints = ['nose',
                           'head bottom', 'head top',
                           'left ear', 'right ear',
                           'left shoulder', 'right shoulder',
                           'left elbow', 'right elbow',
                           'left wrist', 'right wrist',
                           'left hip', 'right hip',
                           'left knee', 'right knee',
                           'left ankle', 'right ankle']

def create_bodypart_colormap(body_keypoints):
    # Use a matplotlib colormap
    colorpalette = sns.color_palette("hls", len(body_keypoints))  # 'tab20' is a good palette for distinct colors

    bodypart_colors = {
        body_keypoints[i]: colorpalette[i] for i in range(len(body_keypoints))
    }

    return bodypart_colors

colormap = create_bodypart_colormap(all_body_keypoints)

In [47]:
# Create a video manage to hold all videos
cropped_video_manager = VideoManager()
# Add all videos as VideoObject to video_manager (optional flag )
cropped_video_manager.add_all_videos(cropped_videos_folder, add_pt_data=True)  # Load class data (pt_data), not the videos themselves

In [48]:
cropped_video_id = 'cropped_vid_35_F-_c'

In [49]:
import json
dir = '/home/daphne/Documents/GMA/codes/output/labeled'
file_path = os.path.join(dir, "35_F-_c.extreme_keypoints.cropped.json")
with open(file_path, 'r') as f:
    cropped_keypoint_labels = json.load(f)

In [50]:
cropped_keypoint_labels

{'0': {'head top': {'x': 402, 'y': 116},
  'left elbow': {'x': 476, 'y': 326},
  'right elbow': {'x': 152, 'y': 303},
  'left wrist': {'x': 454, 'y': 246},
  'right wrist': {'x': 92, 'y': 318},
  'left knee': {'x': 389, 'y': 645},
  'right knee': {'x': 172, 'y': 620},
  'left ankle': {'x': 307, 'y': 730},
  'right ankle': {'x': 185, 'y': 715}}}

In [51]:
select_frame = '0'
keypoints = cropped_keypoint_labels[select_frame].values()

# Extract x and y coordinates and convert to a NumPy array
coords = np.array([[point['x'], point['y']] for point in keypoints])

In [52]:
print(coords)

[[402 116]
 [476 326]
 [152 303]
 [454 246]
 [ 92 318]
 [389 645]
 [172 620]
 [307 730]
 [185 715]]


In [53]:
coords[:,0]

array([402, 476, 152, 454,  92, 389, 172, 307, 185])

In [54]:
cropped_video_object = cropped_video_manager.get_video_object(cropped_video_id)

In [55]:
cropped_video_object.load_video()

Loading video cropped_vid_35_F-_c


In [56]:
color_list = [colormap[keypoint] for keypoint in cropped_keypoint_labels[select_frame].keys()]

In [58]:
# draw query_points on cropped video
fig, ax = plt.subplots(figsize=(10, 5))
ax.imshow(np.array(cropped_video_object.video[int(select_frame)]))
ax.scatter(coords[:, 0], coords[:, 1], marker="o", color=color_list, s=25)
plt.show(block=False)

<IPython.core.display.Javascript object>